# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8294ce86fe38f39f3c92f576f42d1793864b28878e83df78dbc78401bcf3fc5d0d7bf2abfc057bca99761c8673c21bc22add11542aec66388358afb8afcba81b

test:
  secret_key_base: 4b1e2edb0121957e1b4500b201764804cead7402facef912244de309688be9026c931346db891fa8e161d6200721a3b544ae38210b39f24710055868518ef24e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
